repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-termcolor
          - types-PyYAML

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

#  Copied over from litdata repo
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        additional_dependencies: [ tomli ]
        args: [ "--in-place" ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff-format
      - id: ruff
        args: [ "--fix", "--preview" ]
